spring:
  profiles.active: dev
---
spring:
  profiles: default

doge:
  wow: 10
  such: so
  very: true

---
spring:
  profiles: dev

doge:
  wow: 800000000
  such: saoudsfsdffdfd
  very: falsefsfsdsfsdf

---
spring:
  profiles: prod

doge:
  wow: JJJJJJJJJJJ
  such: KKKKKKKKKK
  very: LLLLLLLLL

---
spring:
   profiles: unit-test
doge:
  wow: 4
