spring:
  profiles.active: default
---
spring:
  profiles: default

doge:
  wow: 10
  such: so
  very: true

---
spring:
  profiles: dev

doge:
  wow: 10000
  such: saou
  very: false

---
spring:
  profiles: prod

doge:
  wow: 10
  such: so
  very: true

---
spring:
   profiles: unit-test
doge:
  wow: 4
